create table accounts (
    id bigint generated by default as identity primary key,
    public_id varchar(40) not null unique,
    owner_id varchar(120) not null,
    currency varchar(3) not null,
    status varchar(20) not null,
    available_balance numeric(19, 2) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    version bigint not null default 0,
    constraint chk_accounts_status check (status in ('ACTIVE', 'FROZEN', 'CLOSED')),
    constraint chk_accounts_balance check (available_balance >= 0)
);

create table transfers (
    id bigint generated by default as identity primary key,
    public_id varchar(40) not null unique,
    owner_id varchar(120) not null,
    source_account_id bigint not null references accounts(id),
    destination_account_id bigint not null references accounts(id),
    amount numeric(19, 2) not null,
    currency varchar(3) not null,
    status varchar(20) not null,
    idempotency_key varchar(180),
    description varchar(500),
    failure_reason varchar(500),
    reversal_of_transfer_id bigint references transfers(id),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint chk_transfers_status check (status in ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'REVERSED')),
    constraint chk_transfers_amount check (amount > 0)
);

create table ledger_entries (
    id bigint generated by default as identity primary key,
    public_id varchar(40) not null unique,
    transfer_id bigint not null references transfers(id),
    account_id bigint not null references accounts(id),
    direction varchar(10) not null,
    amount numeric(19, 2) not null,
    currency varchar(3) not null,
    balance_after numeric(19, 2) not null,
    description varchar(500),
    created_at timestamp with time zone not null,
    constraint chk_ledger_direction check (direction in ('DEBIT', 'CREDIT')),
    constraint chk_ledger_amount check (amount > 0)
);

create table idempotency_records (
    id bigint generated by default as identity primary key,
    owner_id varchar(120) not null,
    idempotency_key varchar(180) not null,
    request_hash varchar(128) not null,
    response_body text not null,
    status_code integer not null,
    created_at timestamp with time zone not null,
    expires_at timestamp with time zone not null,
    constraint uq_idempotency_owner_key unique (owner_id, idempotency_key)
);

create table outbox_events (
    id bigint generated by default as identity primary key,
    public_id varchar(40) not null unique,
    event_type varchar(80) not null,
    aggregate_type varchar(80) not null,
    aggregate_id varchar(80) not null,
    payload text not null,
    signature varchar(128),
    status varchar(20) not null,
    retry_count integer not null default 0,
    next_attempt_at timestamp with time zone not null,
    created_at timestamp with time zone not null,
    published_at timestamp with time zone,
    constraint chk_outbox_status check (status in ('PENDING', 'PUBLISHED', 'FAILED'))
);

create table audit_logs (
    id bigint generated by default as identity primary key,
    public_id varchar(40) not null unique,
    owner_id varchar(120) not null,
    actor_id varchar(120) not null,
    action varchar(80) not null,
    resource_type varchar(80) not null,
    resource_id varchar(80) not null,
    correlation_id varchar(120) not null,
    metadata text,
    created_at timestamp with time zone not null
);

create table webhook_endpoints (
    id bigint generated by default as identity primary key,
    owner_id varchar(120) not null,
    url varchar(1000) not null,
    enabled boolean not null default true,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create index idx_accounts_owner_public on accounts(owner_id, public_id);
create index idx_transfers_owner_public on transfers(owner_id, public_id);
create index idx_transfers_source_created on transfers(source_account_id, created_at);
create index idx_transfers_destination_created on transfers(destination_account_id, created_at);
create index idx_ledger_account_created on ledger_entries(account_id, created_at desc);
create index idx_outbox_due on outbox_events(status, next_attempt_at);
create index idx_audit_resource on audit_logs(resource_type, resource_id, created_at);
